### ISSUE TITLE
请问怎么可以拿到k1 k2 k3三个3des解密的密匙

### ISSUE THREAD

**Issue by linzsummer** [rxbit/gdut8021xclient#1]
你好，我最近在研究这个认证，能给点指点吗？

**Comment by rxbit** [comment]
我是逆向Linux客户端得到的。不过现在校园网认证已经不用DES包了。

**Comment by linzsummer** [comment]
又换算法了啊

**Comment by rxbit** [comment]
没注意，还以为是同校的- -！我们学校是改了，不知道你们学校有没有改。自己抓包看看吧。
summer notifications@github.com 於 2014年3月9日星期日 寫道：
