### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Tk-archer** [rxbit/gdut8021xclient#2]
编译时没问题，但是运行时会溢出
我查到一些说法是运行的gcc版太高，球验证
我的是ubuntu14.04 64位 gcc是 gcc version 4.8.2

**Comment by rxbit** [comment]
和gcc无关，我当时用的就是4.8.2，现在4.9也没事，Arch系统
能说说具体情况吗？
我这边路由运行都正常

**Comment by rxbit** [comment]
sorry 最后一次修改忘了提交 :sweat_smile:
现在应该可以了

**Comment by Tk-archer** [comment]
wow，神速回复，我今天再试试
谢谢菊苣
