### ISSUE TITLE
开始很短一段时间之后就出现以下错误并退出

### ISSUE THREAD

**Issue by z5n0w** [rxbit/gdut8021xclient#4]
[ ] Client: Start.
..[ 2] Server: Request Identity!
[ 2] Client: Response Identity.
[ 3] Server: Request MD5-Challenge!
[ 3] Client: Response MD5-Challenge.
[ 4] Server: (H3C data)
[ 4] Server: Success.
[ 5] Server: Failure.
[ ] Client: Start.
[ 2] Server: Request Identity!
[ 2] Client: Response Identity.
[ 3] Server: Request MD5-Challenge!
[ 3] Client: Response MD5-Challenge.
[ 4] Server: (H3C data)
[ 4] Server: Success.
[ 1] Server: Request Identity!
[ 1] Client: Response Identity.
[ 5] Server: Request (type:20)!
Error! Unexpected request type

**Comment by rxbit** [comment]
应该是服务器增加了新的请求类型。
我不在学校，不能测试。
你抓包看看原客户端是怎么处理的，看看能不能自己改吧。
可以的话请发一份抓包过来。

**Comment by dgeibi** [comment]
http://yunpan.cn/cFhtryeg4wtfw （提取码：d31f）
AsustekC_15:03:57

**Comment by rxbit** [comment]
没发现你所说的包。
我在 ddafe4171dd8a1d04ce40a061be16912e8fe5ac4 中去掉了AVAILABLE(type=20)的相关处理。
当时把没用的都删掉了，没想到现在用上了。。。

**Comment by dgeibi** [comment]
我本机Source是 AsustekC_15:03:57

**Comment by rxbit** [comment]
我知道，但Success之后就没有其他包了。其他机子也没有收到Request Available。
![image](https://cloud.githubusercontent.com/assets/1555218/10903004/d41051f8-823f-11e5-8800-3c4099810733.png)
或许你需要放置一段时间🙃

**Comment by dgeibi** [comment]
http://yunpan.cn/cFaTMWx5tqusg （提取码：e70a）

**Comment by rxbit** [comment]
抱歉，还是没看到出问题的包
![image](https://cloud.githubusercontent.com/assets/1555218/10903701/6f88ce4c-8247-11e5-9d41-6e2cc3cc5511.png)

> ```
>                    ^ 上面这字节应为0x14
> ```

会不会是服务器又改回去了呢？
你确定还会出现这个错误？

> [ 5] Server: Request (type:20)!
> Error! Unexpected request type

**Comment by z5n0w** [comment]
确实最近的log里面也没有request avaliable 了
