### ISSUE TITLE
编译得到ipk 装上后 -ash: njit-client: not found

### ISSUE THREAD

**Issue by dgeibi** [rxbit/gdut8021xclient#5]
OpenWrt 15.05
libpcap 1.1.1

**Comment by dgeibi** [comment]
![default](https://cloud.githubusercontent.com/assets/2224764/10963795/04936712-83de-11e5-8a7a-0044a5cb2805.PNG)

**Comment by rxbit** [comment]
应该是没装成功

**Comment by dgeibi** [comment]
软件列表里有 njit client  ，njit client web 的页面可以打开

**Comment by rxbit** [comment]
到usr/bin看看，可能叫别的名字
或者直接解压ipk看看

**Comment by dgeibi** [comment]
debian-binart
data.tar.gz---/usr/sbin/njit-client
           ---/lib/upgrade/keep.d/njit8021xclient

control.tar.gz
-prerm
-postinst
-control

**Comment by dgeibi** [comment]
路由器上也有 /usr/sbin/njit-client 但还是 not found

**Comment by rxbit** [comment]
那直接运行/usr/sbin/njit-client

```
#/usr/sbin/njit-client 3xxxxxxxx xxxxx …..
```

可能是环境变量出问题了

**Comment by hazytint** [comment]
```
# /usr/sbin/njit-client 3xxxxxxxx xxxxx
```

**Comment by dgeibi** [comment]
依旧 not found 尝试装 libopenssl 也没用
环境变量 里也有 /usr/sbin ，里面的其他文件能执行
找到 stackoverflow 上的 [ELF file exists in /usr/bin but turns out “-ash: file: not found](http://stackoverflow.com/questions/31385121/elf-file-exists-in-usr-bin-but-turns-out-ash-file-not-found)

**Comment by dgeibi** [comment]
装了 14.07 的openwrt
安装 njit-client 报错
//usr/lib/opkg/info/njit8021xclient.postinst: line 4: default_postinst: not found
Collected errors:
- pkg_run_script: package "njit8021xclient" postinst script returned status 127.
- opkg_configure: njit8021xclient.postinst returned 127.

依旧not found

**Comment by rxbit** [comment]
看看这个http://www.ddhow.com/blog/postinst.html

**Comment by dgeibi** [comment]
试了 ，结果还是 not found
尝试 编译 scutclient 结果也是 not found ，怀疑编译环境有问题

**Comment by dgeibi** [comment]
所以你的 Linux 是哪个

**Comment by rxbit** [comment]
Archlinux ， Kail 都试过的

Xavier Peng notifications@github.com於 2015年11月9日 週一，下午6:24寫道：

**Comment by dgeibi** [comment]
换成 kali 和 openwrt 15.05 编译成功且正常工作

**Comment by rxbit** [comment]
祝玩的开心😄
